config/routes.rb
Calagator::Application.routes.draw do
  match 'omfg' => 'site#omfg'
  match 'hello' => 'site#hello'

  match 'about' => 'site#about'

  match 'opensearch.:format' => 'site#opensearch'

  resources :events do
    collection do
      post :squash_many_duplicates
      get :search
      get :duplicates
    end

    member do
      get :clone
    end
  end

  resources :sources do
    collection do
      post :import
    end
  end

  resources :venues do
    collection do
      post :squash_many_duplicates
      get :map
      get :duplicates
    end
  end

  resources :versions, :only => [:edit]
  resources :changes, :controller => 'paper_trail_manager/changes'
  match 'recent_changes' => redirect("/changes")
  match 'recent_changes.:format' => redirect("/changes.%{format}")

  match 'css/:name' => 'site#style'
  match 'css/:name.:format' => 'site#style'

  match '/' => 'site#index', :as => :root
  match '/index' => 'site#index'
  match '/index.:format' => 'site#index'

end

app/models/source.rb
# == Schema Information
# Schema version: 20110604174521
#
# Table name: sources
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  url         :string(255)
#  imported_at :datetime
#  created_at  :datetime
#  updated_at  :datetime
#  reimport    :boolean
#

# == Source
#
# A model that represents a source of events data, such as feeds for hCal, iCal, etc.
class Source < ActiveRecord::Base
  include SearchEngine

  validate :assert_url

  has_many :events,  :dependent => :destroy
  has_many :venues,  :dependent => :destroy
  has_many :updates, :dependent => :destroy

  scope :listing, :order => 'created_at DESC'

  has_paper_trail

  xss_foliate
  include DecodeHtmlEntitiesHack

  # Return a newly-created or existing Source record matching the given
  # attributes. The +attrs+ hash is the same format as used when calling
  # Source::new.
  #
  # This method is intended to supplement the import process by providing a
  # single Source record for each unique URL, thus when multiple people import
  # the same URL, there will only be one Source record.
  #
  # The :reimport flag is given special handling: If the original Source record
  # has this set to true, it will never be set back to false by this method.
  # The intent behind this is that if one person wants this Source reimported,
  # the reimporting shouldn't be disabled by someone else manually importing it
  # without setting the reimport flag. If someone really wants to turn off
  # reimporting, they should edit the source.
  def self.find_or_create_from(attrs={})
    if attrs && attrs[:url]
      source = Source.find_or_create_by_url(attrs[:url])
      attrs.each_pair do |key, value|
        if key.to_sym == :reimport
          source.reimport = true if ! source.reimport && value
        else
          source.send("#{key}=", value) if source.send(key) != value
        end
      end
      source.save if source.changed?
      return source
    else
      return Source.new(attrs)
    end
  end

  # Create events for this source. Returns the events created. URL must be set
  # for this source for this to work.
  def create_events!(opts={})
    cutoff = Time.now.yesterday # All events before this date will be skipped
    events = []
    for event in self.to_events(opts)
      if opts[:skip_old]
        next if event.title.blank? && event.description.blank? && event.url.blank?
        next if event.old?
      end

      # Skip invalid events that start after they end
      next if event.end_time && event.end_time < event.start_time

      # convert to local time, because time zone is simply discarded when event is saved
      event.start_time.localtime
      event.end_time.localtime if event.end_time

      # clear duplicate_of_id field in case to_events picked up orphaned duplicate
      # TODO clear the duplicate_of_id at the point where the object is created, not down here
      event.duplicate_of_id = nil if event.duplicate_of_id
      event.save!
      if event.venue
        event.venue.duplicate_of_id = nil if event.venue.duplicate_of_id
        event.venue.save! if event.venue
      end
      events << event
    end
    self.save!
    return events
  end

  # Normalize the URL.
  def url=(value)
    begin
      url = URI.parse(value.strip)
      url.scheme = 'http' unless ['http','https','ftp'].include?(url.scheme) || url.scheme.nil?
      write_attribute(:url, url.scheme.nil? ? 'http://'+value.strip : url.to_s)
    rescue URI::InvalidURIError => e
      false
    end
  end

  # Returns an Array of Event objects that were read from this source.
  #
  # Options:
  # * :url -- URL of data to import. Defaults to record's #url attribute.
  # * :skip_old -- Should old events be skipped? Default is true.
  def to_events(opts={})
    self.imported_at = Time.now
    if valid?
      opts[:url] ||= self.url
      [].tap do |events|
        SourceParser.to_abstract_events(opts).each do |abstract_event|
          event = Event.from_abstract_event(abstract_event, self)

          events << event
        end
      end
    else
      raise ActiveRecord::RecordInvalid, self
    end
  end

  # Return the name of the source, which can be its title or URL.
  def name
    [title,url].detect{|t| !t.blank?}
  end

private

  # Ensure that the URL for this source is valid.
  def assert_url
    begin
      URI.parse(url)
      return true
    rescue URI::InvalidURIError => e
      errors.add("url", "has invalid format")
      return false
    end
  end

end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  MAXIMUM_EVENTS_TO_DISPLAY_IN_FLASH = 5
  
  # Import sources
  def import
    @source = Source.find_or_create_from(params[:source])
    @events = nil # nil means events were never assigned, while [] means no events were found

    valid = @source.valid?
    if valid
      begin
        @events = @source.create_events!
      rescue SourceParser::NotFound => e
        @source.errors.add(:base, "No events found at remote site. Is the event identifier in the URL correct?")
      rescue SourceParser::HttpAuthenticationRequiredError => e
        @source.errors.add(:base, "Couldn't import events, remote site requires authentication.")
      rescue OpenURI::HTTPError => e
        @source.errors.add(:base, "Couldn't download events, remote site may be experiencing connectivity problems. ")
      rescue Errno::EHOSTUNREACH => e
        @source.errors.add(:base, "Couldn't connect to remote site.")
      rescue SocketError => e
        @source.errors.add(:base, "Couldn't find IP address for remote site. Is the URL correct?")
      rescue Exception => e
        @source.errors.add(:base, "Unknown error: #{e}")
      end
    end

    respond_to do |format|
      if valid && @events && @events.size > 0
        # TODO move this to a view, it currently causes a CGI::Session::CookieStore::CookieOverflow if the flash gets too big when too many events are imported at once
        s = "<p>Imported #{@events.size} entries:</p><ul>"
        @events.each_with_index do |event, i|
          if i >= MAXIMUM_EVENTS_TO_DISPLAY_IN_FLASH
            s << "<li>And #{@events.size - i} other events.</li>"
            break
          else
            s << "<li>#{help.link_to(event.title, event_url(event))}</li>"
          end
        end
        s << "</ul>"
        flash[:success] = s

        format.html { redirect_to(events_path) }
        format.xml  { render :xml => @source, :events => @events }
      else
        flash[:failure] = @events.nil? \
          ? "Unable to import: #{@source.errors.full_messages.to_sentence}" \
          : "Unable to find any upcoming events to import from this source"

        format.html { render :action => "new" }
        format.xml  { render :xml => @source.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # GET /sources
  # GET /sources.xml
  def index
    @sources = Source.listing

    respond_to do |format|
      format.html { @sources = @sources.paginate(:page => params[:page], :per_page => params[:per_page]) }
      format.xml  { render :xml => @sources }
    end
  end

  # GET /sources/1
  # GET /sources/1.xml
  def show
    begin
      @source = Source.find(params[:id], :include => [:events, :venues])
    rescue ActiveRecord::RecordNotFound => e
      flash[:failure] = e.to_s if params[:id] != "import"
      return redirect_to(new_source_path)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @source }
    end
  end

  # GET /sources/new
  # GET /sources/new.xml
  def new
    @source = Source.new
    @source.url = params[:url] if params[:url].present?

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @source }
    end
  end

  # GET /sources/1/edit
  def edit
    @source = Source.find(params[:id])
  end

  # POST /sources
  # POST /sources.xml
  def create
    @source = Source.new(params[:source])

    respond_to do |format|
      if @source.save
        flash[:notice] = 'Source was successfully created.'
        format.html { redirect_to( source_path(@source) ) }
        format.xml  { render :xml => @source, :status => :created, :location => @source }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sources/1
  # PUT /sources/1.xml
  def update
    @source = Source.find(params[:id])

    respond_to do |format|
      if @source.update_attributes(params[:source])
        flash[:notice] = 'Source was successfully updated.'
        format.html { redirect_to( source_path(@source) ) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.xml
  def destroy
    @source = Source.find(params[:id])
    @source.destroy

    respond_to do |format|
      format.html { redirect_to(sources_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sources_helper.rb
module SourcesHelper
  # Return HTML with a link to the the external source URL.
  def source_url_link(source)
    return link_to source.url, source.url, { :rel => "nofollow", :target => "_BLANK" }
  end
end

app/views/sources/edit.html.erb
<h1>Editing source</h1>

<%= semantic_form_for(@source) do |f| %>
  <%= f.inputs do %>
    <%= f.input :url %>
    <%= f.input :reimport, :label => "Re-import?" %>
  <% end %>
  <%= f.actions :submit %>
<% end %>

<%= link_to 'Show', @source %> |
<%= link_to 'Back', sources_path %>

app/views/sources/index.html.erb
<h1>Listing sources</h1>

<table>
  <tr>
    <th>Manage</th>
    <th>URL</th>
  </tr>

  <% for source in @sources %>
  <tr class="<%= cycle 'odd', 'even' %>">
    <td>
      <%= link_to 'Show', source %> | 
      <%= link_to 'Destroy', source, :confirm => 'Are you sure?', :method => :delete %>
    </td>
    <td><%= source_url_link source %></td>
  </tr>
  <% end %>
</table>

<br />

<%= will_paginate @sources %>

app/views/sources/new.html.erb
<%= render :partial => 'site/appropriateness_message' %>

<%= semantic_form_for(@source, :html => {:id => 'source_form', :class => 'standard_form'}, :url => { :action => :import }) do |f| %>
  <%= f.inputs :name => "Import a source" do %>
    <li class='input'>
      <p class='inline-hints'>
        Import one or more events from a feed or web page in one of the following formats:
        <%= SourceParser.labels.to_sentence %>
      </p>
    </li>
    <%= f.input :url, :label => "URL" %>
    <% focus_on '#source_url' %>

    <%# FIXME Igal has disabled reimport UI because people are adding almost all new events with re-import, which means that they're almost all generating duplicates and I'm completely overwhelmed with having to use the horrible squashing UI to deal with them. %>
    <% if false %>
      <%= f.input :reimport, :label => "Re-import?", :hint => "(Regularly check this source and import new events automatically?)" %>
    <% end %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :label => "Import" %>
  <% end %>

  <%= f.inputs do %>
    <li class='input'>
      <p class='inline-hints'>
      <b>Bookmarklet</b>: Import pages faster by adding the following bookmark to your browser's bookmarks and click it when you're visiting a webpage that contains events that you'd like to import:
      <%= link_to "Add to #{SETTINGS.name}", "javascript:d=document;q=(d.location.href);w=window;location.href='#{new_source_url}?url='+escape(q);" %>
      </p>
    </li>
  <% end %>
<% end %>

app/views/sources/show.html.erb
<% content_for :discovery_insert do %>
  <link rel="alternate" type="application/x-wiki" title="Edit this page" href="<%= edit_source_url(@source) %>" />
<% end %>

<p>
  <b>URL:</b>
  <%= source_url_link @source %>
</p>

<p>
   <b>Events:</b>
   <%= render :partial => 'events/list', :locals => { :events =>  @source.events } %>
</p>

<%= link_to 'Back', sources_path %> |
<%= link_to 'Destroy', @source, :confirm => 'Are you sure?', :method => :delete %>