config/routes.rb
Calagator::Application.routes.draw do
  match 'omfg' => 'site#omfg'
  match 'hello' => 'site#hello'

  match 'about' => 'site#about'

  match 'opensearch.:format' => 'site#opensearch'

  resources :events do
    collection do
      post :squash_many_duplicates
      get :search
      get :duplicates
    end

    member do
      get :clone
    end
  end

  resources :sources do
    collection do
      post :import
    end
  end

  resources :venues do
    collection do
      post :squash_many_duplicates
      get :map
      get :duplicates
    end
  end

  resources :versions, :only => [:edit]
  resources :changes, :controller => 'paper_trail_manager/changes'
  match 'recent_changes' => redirect("/changes")
  match 'recent_changes.:format' => redirect("/changes.%{format}")

  match 'css/:name' => 'site#style'
  match 'css/:name.:format' => 'site#style'

  match '/' => 'site#index', :as => :root
  match '/index' => 'site#index'
  match '/index.:format' => 'site#index'

end

app/helpers/events_helper.rb
module EventsHelper
  include TimeRangeHelper # provides normalize_time

  def today_tomorrow_or_weekday(record)
    # TODO Figure out if there's any need for this method beyond having a way of conditionally displaying the 'Started' information. As far as I can tell, there's no need to display the 'Today' or 'Tomorrow' rather than the weekday because each event already has a header to its left that can say 'Today' or 'Tomorrow'.
#    if record.start_time.to_date == Time.today.to_date
#      'Today'
#    elsif record.start_time.to_date == (Time.today+1.day).to_date
#      'Tomorrow'
#    elsif record.ongoing?
    if record.ongoing?
      "Started #{record.start_time.strftime('%A')}"
    else
      record.start_time.strftime('%A')
    end
  end

# calculate rowspans for an array of events
# argument:  array of events
# returns:  rowspans, an array in which each entry corresponds to an event in events;
# each entry is number of rows spanned by today_tomorrow_weekday entry, if any, to left of event
# entry will be > 0 for first event of day, 0 for other events
  def calculate_rowspans(events)
    previous_start_time = nil
    rowspans = Array.new(events.size, 0)
    first_event_of_day = 0

    events.each_with_index do |event, index|
      new_day = previous_start_time.nil? || (previous_start_time.to_date != event.start_time.to_date)
      if new_day
        first_event_of_day = index
      end
      rowspans[first_event_of_day] += 1
      previous_start_time = event.start_time
    end

    return rowspans
  end

  def google_maps_url(address)
    return "http://maps.google.com/maps?q=#{cgi_escape(address)}"
  end

  #---[ Event sorting ]----------------------------------------------------

  # Return a link for sorting by +key+ (e.g., "name").
  def events_sort_link(key)
    if key.present?
      link_to(Event::sorting_label_for(key, @tag.present?), url_for(params.merge(:order => key)))
    else
      link_to('Default', url_for(params.tap { |o| o.delete :order }))
    end
  end

  # Return a human-readable label describing what the sorting +key+ is.
  def events_sort_label(key)
    if key.present? or @tag.present?
      sanitize " by <strong>#{Event::sorting_label_for(key, @tag.present?)}.</strong>"
    else
      nil
    end
  end

  #---[ Google Calendar export ]--------------------------------------------

  # Time format used for Google Calendar exports
  GOOGLE_TIME_FORMAT = "%Y%m%dT%H%M%SZ"

  # Return a time span using Google Calendar's export format.
  def format_google_timespan(event)
    end_time = event.end_time || event.start_time
    "#{event.start_time.utc.strftime(GOOGLE_TIME_FORMAT)}/#{end_time.utc.strftime(GOOGLE_TIME_FORMAT)}"
  end

  # Return a Google Calendar export URL.
  def google_event_export_link(event)
    result = "http://www.google.com/calendar/event?action=TEMPLATE&trp=true&text=" << cgi_escape(event.title)

    result << "&dates=" << format_google_timespan(event)

    if event.venue
      result << "&location=" << cgi_escape(event.venue.title)
      if event.venue.geocode_address.present?
        result << cgi_escape(", " + event.venue.geocode_address)
      end
    end

    if event.url.present?
      result << "&sprop=website:" << cgi_escape(event.url.sub(/^http.?:\/\//, ''))
    end

    if event.description.present?
      details = "Imported from: #{event_url(event)} \n\n#{event.description}"
      details_suffix = "...[truncated]"
      overflow = 1024 - result.length
      if overflow > 0
        details = "#{details[0..(overflow - details.size - details_suffix.size - 1)]}#{details_suffix}"
      end
      result << "&details=" << cgi_escape(details)
    end

    return result
  end

  #---[ Feed links ]------------------------------------------------------

  # Returns a URL for an events feed.
  #
  # @param [Hash] filter Options for filtering. If values are defined, returns
  #   a link to all events. If a :query is defined, returns a link to search
  #   events' text by that query. If a :tag is defined, returns a link to search
  #   events with that tag.
  # @param [Hash] common Options for the URL helper, such as :protocol, :format
  #   and such.
  #
  # @raise [ArgumentError] Raised if given invalid filter options.
  #
  # @return [String] URL
  def _events_feed_linker(filter={}, common={})
    # Delete blank filter options because this method is typically called with
    # both a :tag and :query filter, but only one will actually be set.
    filter.delete_if { |key, value| value.blank? }

    if (unknown = filter.keys - [:query, :tag]).present?
      raise ArgumentError, "Unknown option(s): #{unknown.inspect}"
    end

    return filter.present? ?
      search_events_url(common.merge(filter)) :
      events_url(common)
  end

  GOOGLE_EVENT_SUBSCRIBE_BASE = "http://www.google.com/calendar/render?cid="

  # Returns a Google Calendar subscription URL.
  #
  # @see #_events_feed_linker for details on parameters and exceptions.
  def google_events_subscription_link(filter={})
    link = _events_feed_linker(filter, :format => "ics")
    return "#{GOOGLE_EVENT_SUBSCRIBE_BASE}#{CGI::escape(link)}"
  end

  # Returns an iCalendar subscription URL.
  #
  # @see #_events_feed_linker for details on parameters and exceptions.
  def icalendar_feed_link(filter={})
    return _events_feed_linker(filter, :protocol => "webcal", :format => "ics")
  end

  # Returns an iCalendar export URL.
  #
  # @see #_events_feed_linker for details on parameters and exceptions.
  def icalendar_export_link(filter={})
    return _events_feed_linker(filter, :format => "ics")
  end

  # Returns an ATOM subscription URL.
  #
  # @see #_events_feed_linker for details on parameters and exceptions.
  def atom_feed_link(filter={})
    return _events_feed_linker(filter, :format => "atom")
  end

  #--[ Sharing buttons ]-----------------------------------------

  # Will increase the maximum length of either the event title or venue
  # if one of the two is shorter than the maximum: 46

  def tweet_text_sizer(event)
    title_length = event.title.length
    venue_length = (event.venue.try(:title) || "").length
    if (title_length > 46) && (venue_length < 46)
      title_length = 46 + (46-venue_length)
    elsif (title_length > 46)
      title_length = 46
    end

    if (venue_length > 46) && (title_length < 46)
      venue_length = 46 + (46-title_length)
    elsif (venue_length > 46)
      venue_length = 46
    end
    result = {:title => title_length, :venue => title_length}
  end

  # Tweet button text

  def tweet_text(event)

    lengths = tweet_text_sizer(event)

    result = []
    result << "#{truncate(event.title, :length => lengths[:title])} -"
    result << event.start_time.strftime("%I:%M%p %m.%d.%Y") # "04:00PM 08.01.2012"
    result << "@ #{truncate(event.venue.title, :length => lengths[:venue])}" if event.venue

    return result.join(" ")
  end

  def shareable_event_url(event)
    if event.persisted?
      if Rails.env.development?
        SETTINGS.url.sub(/\/$/,'') + event_path(event)
      else
        event_url(event)
      end
    end
  end

end

app/views/events/_form.html.erb
<%
# USAGE: Display a form for creating or editing an event.
#
# VARIABLES:
# * event: An new or existing Event instance.
%>

<% content_for :css_insert do %>
  <%= stylesheet_link_tag 'forms' %>
<% end %>

<% content_for :javascript_insert do %>
  <%= javascript_include_tag 'forms' %>
  <script>
    var completed_title = '';
    $(document).ready(function(){
      
      // Initialize autocompletion for venues
      $("input.autocomplete").attr('autocomplete', 'off').autocomplete({
        source: "/venues.js",
        minLength: 2,
        search: function(event, ui) {
          //$("#event_venue_loading").show();
          $("#event_venue_id").val('');
        },
        select: function(event, ui) {
          $('input.autocomplete').val( ui.item.title );
          $("#event_venue_id").val( ui.item.id );

          return false;
        }
      }).data( "autocomplete" )._renderItem = function( ul, item ) {
        var short_address = (item.street_address && item.street_address.length > 0)
                              ? item.street_address+", "+item.locality+" "+item.region
                              : item.address;
        return $( "<li><a><strong>"+item.title+"</strong><br />"+short_address+"</a></li>" )
                .data( "item.autocomplete", item )
                .appendTo(ul);
      };
      
      // Initialize date and time pickers
      $('.date_picker').datepicker({ dateFormat: 'yy-mm-dd' });
      $('.time_picker').timePicker({
        show24Hours:false,
        separator:':',
        step: 30});

      // Update "time_end" to have the same offset from "time_start" if the "time_start" changes, and displays a highlight to alert the user.
      var oldTime = $.timePicker("#time_start").getTime();
      $("#time_start").change(function() {
        if ($("#time_end").val()) { // Only update when second input has a value.
          // Calculate duration.
          var duration = ($.timePicker("#time_end").getTime() - oldTime);
          var time = $.timePicker("#time_start").getTime();
          // Calculate and update the time in the second input.
          $.timePicker("#time_end").setTime(new Date(new Date(time.getTime() + duration)));
          $('#time_end').effect('highlight', {}, 3000);
          oldTime = time;
        }
      });

      // Update "date_end" so that it is the same as "date_start" if "date_start" is changed to after "date_end", and displays a highlight to alert the user..
      $("#date_start").change(function() {
        // Only update when end value is defined.
        if ($("#date_end").val()) { 
          // Only update when end value is before start value.
          var startDate = $.datepicker.parseDate('yy-mm-dd', $('#date_start').val());
          var endDate = $.datepicker.parseDate('yy-mm-dd', $('#date_end').val());
          if (endDate < startDate) {
            $('#date_end').val($('#date_start').val());
            $('#date_end').effect('highlight', {}, 3000);
          }
        }
      });
    });
  </script>
<% end %>

<% if params[:preview] && event.valid? -%>
<div id="event_preview">
    <h2>Preview your event</h2>

    <%= render :partial => "item", :locals => { :event => event, :has_contentbar => false } %>
</div>
<% end -%>

<%= semantic_form_for(event, :html => {:id => 'event_form', :class => 'standard_form', :novalidate => 'novalidate'}) do |f| %>
  <%= f.inputs :name => "#{'Editing: ' unless event.new_record?} <em>#{event.title}</em>".html_safe do %>
    <%= f.input :title, :label => "Event Name" %>
    <% focus_on '#event_title' %>
    <li class="string input required stringish" id="event_venue_title_input">
      <%= f.label :venue_id, "Venue", :class => 'label' %>
      <%= text_field_tag 'venue_name', '', :class=> 'autocomplete', :value => !event.venue.nil? ? event.venue.title : params[:venue_name] %>
      <%= hidden_field(:event, :venue_id, :value => (!event.venue.nil? ? event.venue.id : params[:event_venue_id])) %>
      <%= image_tag "spinner.gif", :id=> "event_venue_loading", :style => "display: none; margin-left: 0.5em;" %>
      <p class='inline-hints'>
        Type the name of a venue to search. If it doesn't exist, we'll create it for you.
      </p>
    <li>
    <li id="event_times" class='input'>
      <%= f.label :when, "When", :class => 'label' %>
      <%
        present = Time.now
        # Provide initial default values for the start_time and end_time rounded to the upcoming hour.
        event.start_time ||= present + (60.minutes - present.min.minutes) - present.sec
        event.end_time   ||= present + (60.minutes - present.min.minutes) - present.sec + 1.hour
      %>
        <%= text_field_tag 'start_date', event.start_time.to_date, :id => 'date_start', :class => 'date_picker' %>
        <%= text_field_tag 'start_time', event.start_time.strftime('%I:%M %p'), :id => 'time_start', :class => 'time_picker' %>
        <span class="to">to</span>
        <%= text_field_tag 'end_time', event.end_time.strftime('%I:%M %p'), :id => 'time_end', :class => 'time_picker' %>
        <%= text_field_tag 'end_date', event.end_time.to_date, :id => 'date_end', :class => 'date_picker' %>
        <%= f.semantic_errors :start_date, :start_time, :end_date, :end_time %>
    </li>
    <%= f.input :url, :label => 'Website' %>
    <%= f.input :description,
                :input_html => {:rows => 12},
                :hint => "(Format text using #{link_to("Markdown", "http://www.simpleeditions.com/59001/markdown-an-introduction", :target => "_blank")} and HTML)".html_safe %>
    <%= f.input :venue_details, :required => false,
                :input_html => {:rows => 4},
                :hint => "(Event-specific details like the room number, or who to call to be let into the building.)" %>
    <%= f.input :tag_list, :required => false,
                :label => 'Tags',
                :hint => "(Tags are comma-separated keywords that make it easier to find your event and boost its position in searches. You can also use a tag like <code>plancast:plan=ABCD</code> to associate this with a particular <a href='http://plancast.com/'>Plancast</a> event, or a tag like <code>epdx:group=1234</code> to associate the event with a particular <a href='http://epdx.org/'>ePDX</a> group)".html_safe %>
    <li class='trap'>
      <%= label 'trap', 'field', "Leave this field blank or we'll think you're a robot." %>
      <%= text_field_tag 'trap_field', params[:trap_field] %>
    </li>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, :label => "Preview", :button_html => {:name => 'preview'} %>
    <%= f.action :submit %>
  <% end %>
<% end %>

app/views/events/_hcal.html.erb
<div class="vevent">
  <h1 class="summary"><%= @event.title %></h1>
  <div class='date'><%= normalize_time(@event) -%></div>
  <% unless @event.venue.blank? %>
    <div class="location vcard">
    <a class="url" href='<%= url_for venue_url(@event.venue) %>'><span class='fn org'><%= @event.venue.title -%></span></a>
    <div class="adr">
      <% if !@event.venue.street_address.blank? -%>
        <div class="street-address"><%= @event.venue.street_address -%></div>
      <% end %>
      <% if !@event.venue.locality.blank? -%>
        <span class="locality"><%= @event.venue.locality -%></span>
      <% end -%>
      <% if !@event.venue.region.blank? -%>
        , <span class="region"><%= @event.venue.region -%></span>
      <% end -%>
      <% if !@event.venue.postal_code.blank? -%>
        <span class="postal-code"><%= @event.venue.postal_code -%></span>
      <% end -%>
      <% if !@event.venue.country.blank? -%>
        <div class='country-name'><%= @event.venue.country -%></div>
      <% end -%>
      <% if @event.venue && @event.venue.has_full_address? -%>
        (<a href='<%=google_maps_url(@event.venue.full_address) -%>'>map</a>)
      <% end -%>
    </div>
    </div>
  <% end -%>
  <% unless @event.description.blank? -%>
  <div class="description">
    <%= format_description(@event.description) %>
  </div>
  <% end -%>
  <% unless @event.url.blank? -%>
  <h3>Links</h3>
  <ul>
    <li><%= link_to "Website", @event.url, :class => "url" -%></li>
  </ul>
  <% end -%>
</div>

app/views/events/_item.html.erb
<%
# VARIABLES:
# * event: An Event instance.
# * has_contentbar: Should room be left to display a contentbar on the side? Defaults to true.

has_contentbar = local_assigns.has_key?(:has_contentbar) ? local_assigns[:has_contentbar] : true

html_classes = "single_event"
html_classes << " contentbar" if has_contentbar
%>
<div id="fb-root"></div>
<div class="<%= html_classes %>">
  <div class="vevent h-event" itemscope itemtype="http://schema.org/Event">
    <h1 class="summary p-name" itemprop="name"><%= event.title %></h1>
    <meta itemprop="startDate" content="<%= event.start_time.to_time.iso8601 %>">
    <% if event.end_time %>
      <meta itemprop="endDate" content="<%= event.end_time.to_time.iso8601 %>">
    <% end %>
    <div class='date'><%= normalize_time(event) -%></div>
      <% unless event.venue.blank? %>
      <div class="clearfix location p-location h-card vcard<%= " closed" if event.venue.closed? %>"  itemprop="location" itemscope itemtype="http://schema.org/Place">
      <%= google_map event %>
          <a class="url u-url" href='<%= event.venue.new_record? ? "#" : venue_url(event.venue) %>'>
            <span class='fn org p-name' itemprop="name"><%= event.venue.title -%></span>
          </a>
          <% if event.venue.closed? %><p class='closed_callout'>This venue is no longer open for business.</p><% end %>
          <div class="adr p-adr h-adr" itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
          <% if !event.venue.street_address.blank? -%>
          <div class="street-address p-street-address" itemprop="streetAddress"><%= event.venue.street_address -%></div>
          <% end %>
          <% if !event.venue.locality.blank? -%>
            <span class="locality p-locality" itemprop="addressLocality"><%= event.venue.locality -%></span><%= "," if event.venue.region.present? or event.venue.postal_code.present? or event.venue.country.present? %>
            <% end -%>
            <% if !event.venue.region.blank? -%>
            <span class="region p-region" itemprop="addressRegion"><%= event.venue.region -%></span><%= "," if event.venue.country.present? and not event.venue.postal_code.present? %>
            <% end -%>
            <% if !event.venue.postal_code.blank? -%>
            <span class="postal-code p-postal-code"  itemprop="postalCode"><%= event.venue.postal_code -%></span><%= "," if  event.venue.country.present? %>
            <% end -%>
            <% if !event.venue.country.blank? -%>
            <span class='country-name p-country-name'><%= event.venue.country -%></span>
            <% end -%>
            <% if event.venue && event.venue.has_full_address? -%>
            (<a href='<%=google_maps_url(event.venue.full_address) -%>'>map</a>)
            <% end -%>

            <% if event.venue.wifi? -%>
              <div class='wifi_callout'>Public WiFi</div>
            <% end -%>

            <% if event.venue.access_notes.present? -%>
              <div class="access_notes">
                <h3>Access Notes</h3>
                <%= format_description event.venue.access_notes %>
              </div>
            <% end -%>

            <% unless event.venue_details.blank? -%>
            <p class="p-description">
              <%= format_description(event.venue_details) %>
            </p>
            <% end -%>

      </div>
      <% end -%>
  </div>

    <% unless event.url.blank? -%>
      <h3>Website</h3>
      <div class="website">
        <%= link_to "#{truncate(event.url, :length => 128)}", h(event.url), :class => "url u-url", :rel => "nofollow", 
        :itemprop => "url" %>
      </div>
    <% end -%>

    <% unless event.description.blank? -%>
    <h3>Description</h3>
    <div class="description e-description" itemprop="description">
      <%= format_description(event.description) %>
    </div>
    <% end -%>
    <div class="attendees">
      <script id="attendees-template" type="text/mustache">
        <h3>Attendees</h3>
        <span class='plancast-rsvp'>(<a href="{{plan_url}}">Count me in on Plancast</a>)</span>
        <br />
        <ul>
          {{#attendees}}
            <li>
              {{#username}}<a href='http://plancast.com/{{username}}'><img class='avatar' src='{{pic_square}}'/></a>{{/username}}
              {{^username}}<a href='http://plancast.com/user/{{id}}'><img class='avatar' src='{{pic_square}}'/></a>{{/username}}
            </li>
          {{/attendees}}
        </ul>
      </script>
    </div>
    <% if event.persisted? %>
      <h3>Share</h3>
      <div class="share">
        <a class="fb-share" href="#"
          onclick="
            window.open(
              'https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent('<%= shareable_event_url(event) %>'),
              'facebook-share-dialog',
              'width=626,height=436');
            return false;">
          Share
        </a>
        <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= shareable_event_url(event) %>" data-text="<%= tweet_text(event) %>" data-related="calagator" data-dnt="true">Tweet</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      </div>
    <% end %>
    <% unless event.tags.blank? -%>
    <h3>Tags</h3>
    <div class="tags">
        <%= tag_links_for event %>
    </div>
    <% end %>
  </div>
</div>

app/views/events/_list_item.html.erb
<%
new_day ||= nil
opts ||= {}
opts[:dates] = opts.has_key?(:dates) ? opts[:dates] : true
show_year ||= false
%>
<div class='vevent h-event'>
  <% date_class = (opts[:dates]==false || !new_day) ? ' hidden' : '' -%>
  <div class='list_date<%=date_class%>'>
    <div class='day_of_week'><%= today_tomorrow_or_weekday(event) %></div>
    <%= datetime_format(event.start_time,'%b %d') -%>
    <% if show_year -%>
      <%= datetime_format(event.start_time,'%Y') -%>
    <% end %>
  </div>
  <div class='list_content'>
    <a class='summary p-name u-url' href='<%= url_for event_url(event) %>'><%= event.title %></a>
    <div>
    <%= normalize_time(event, :context => event.start_time.to_date) -%>
    <% if event.venue && !event.venue.title.blank? %>
      <br/><a class='location p-location h-card' href='<%= url_for venue_url(event.venue) %>'><%= event.venue.title -%></a>
    <% end -%>
    </div>
    <% if !event.description.blank? %>
      <div class='description e-description'>
        <%= format_description(event.description) -%>
      </div>
    <% end -%>
    <% if !event.url.blank? -%>
      <%= link_to "Website", h(event.url), :class => "url u-url", :rel => "nofollow" -%>
    <% end -%>
  </div>
</div>

app/views/events/_table.html.erb
<%-
# Arguments:
# * events => Array of Event records.
# * scores => Offer a sort by score, like for search? Default to false.

scores = defined?(scores) ? scores : false

previous_start_time = nil
#show_year ||= false
skipped = 0

# calculate rowspans array for events
# each entry is number of rows spanned by today_tomorrow_weekday entry, if any, to left of event
# entry will be > 0 for first event of day, 0 for other events
rowspans = calculate_rowspans(events)
-%>
<table class='event_table'>
  <thead>
    <tr>
      <th class='date'>Sort By: <%= link_to "Date", url_for(params.merge(:order => 'date')) %></th>
      <th class='event_summary'>
        <%= events_sort_link('name') -%>,
        <%= events_sort_link('venue') -%>
        <%- if scores -%>,
        <%= events_sort_link('score') -%>
        <%- end -%>, 
        <%= events_sort_link(nil) -%>
      </th>
    </tr>
  </thead>
  <tbody>
    <% unless events.size==0 %>
      <% events.each_with_index do |event, index| %>
        <tr class='vevent h-event'>
          <% if rowspans[index] > 0 %>
          <td class='date' rowspan="<%=rowspans[index]%>">
            <div class='day_of_week <%= today_tomorrow_or_weekday(event).downcase -%>'>
              <%= today_tomorrow_or_weekday(event) %>
            </div>
            <% show_year = event.start_time.year != Time.now.year %>
            <%= datetime_format(event.start_time,'%b %d') -%><%= ", "+datetime_format(event.start_time,'%Y') if show_year %>
          </td>
          <% end %>
          <td class='event_summary'>
            <a class='summary p-name u-url' href='<%= url_for event_url(event) %>' name='<%= "event-#{event.id}" %>' id='<%= "event-#{event.id}" %>'><%= event.title %></a><br />
            <%= normalize_time(event, :context => event.start_time.to_date) -%>
            <% if event.venue && !event.venue.title.blank? %>
              <a class='location p-location h-card' href='<%= url_for venue_url(event.venue) %>'><%= event.venue.title -%></a>
            <% end -%>
            <% if !event.description.blank? %>
              <div class='description e-description'>
                <%= format_description(event.description) -%>
              </div>
            <% end -%>
            <% if !event.url.blank? -%>
              <%= link_to "Website", event.url, :class => "url u-url", :rel => "nofollow" -%>
            <% end -%>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan=2>No events were found.</td>
      </tr>
    <% end %>
    <% if skipped > 0 %>
      <tr>
        <td colspan=2>
          <%= link_to "(And #{skipped} more)", events_url %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/edit.html.erb
<%= render '/versions/edit_with_chooser', :record => @event %>

app/views/events/new.html.erb
<div id="new_event_form">
  <%= render :partial => 'site/appropriateness_message' %>

  <%= render :partial => 'form', :locals => {:event => @event} %>
</div>

app/views/events/show.html.erb
<% tabindex_on '#search_field' %>

<% content_for :discovery_insert do %>
  <link rel="alternate" type="application/x-wiki" title="Edit this page" href="<%= edit_event_url(@event) %>" />
<% end %>

<% content_for :open_graph_tags do %>
  <meta property="og:title" content="<%= @event.title %>" />
  <meta property="og:description" content="<%= @event.description %>" />
  <meta property="og:site_name" content="<%= SETTINGS.name %>" />
  <meta property="og:url" content="<%= event_url(@event) %>">
<% end %>

<% content_for :javascript_insert do %>
  <%= javascript_include_tag 'mustache' %>
  <script type='text/javascript'>
    $(function() {
      var plan = $('.external.plancast.plan:first');
      if (plan.length > 0) {
        var plan_id = plan.text().split('=')[1];
        $.getJSON("http://api.plancast.com/02/plans/show.json?jsonp=?",
          { extensions: "attendees",
            plan_id: plan_id },
          function(data) {
            if (data.attendees.length > 0) {
              $('.attendees').append(Mustache.to_html($('#attendees-template').html(), data));
            }
          }
        );
      }
    })
  </script>
<% end %>


<a href="#" id="event_sidebar_toggle" class="expander_toggle">Export or edit this event...</a>

<div id="event_sidebar" class='single_view_right sidebar'>
  <h3 class='first'>Export to</h3>
  <ul>
    <li><%= link_to "Google Calendar", google_event_export_link(@event), :id => "google_calendar_export", :target => "_blank" %></li>
    <li><%= link_to 'iCalendar file', "#{event_url(@event)}.ics" %></li>
    <li>
      <%= link_to_function 'hCalendar markup', '$("#hcal_field").toggle()' %>
      <div id="hcal_field" style="display: none;">
        <%# TODO: Do we actually want to keep providing this? %>
        <%= text_area_tag 'hCalendar',
          h(
            render :partial => 'hcal',
                      :locals => {
                        :event => @event,
                        :show_year => true
                      },
                      :formats => [:html]
          ), :rows => 10, :cols => 80 %>
      </div>
    </li>
  </ul>
<hr />
  <div id='edit_link'>
    <p>
      You can 
      <%= link_to "edit", edit_event_url(@event) %>,
      <%= link_to "clone", clone_event_url(@event) %>,
      or 
      <%= link_to "delete", event_url(@event), :method => :delete, :confirm => "Are you sure?" %>
      this event.
    </p>
  </div>
<hr />
  <div id='metadata'>
      <%= datestamp(@event) %>
  </div>
</div>

<%= render :partial => 'events/item', :locals => {:event => @event} %>