config/routes.rb
Calagator::Application.routes.draw do
  match 'omfg' => 'site#omfg'
  match 'hello' => 'site#hello'

  match 'about' => 'site#about'

  match 'opensearch.:format' => 'site#opensearch'

  resources :events do
    collection do
      post :squash_many_duplicates
      get :search
      get :duplicates
    end

    member do
      get :clone
    end
  end

  resources :sources do
    collection do
      post :import
    end
  end

  resources :venues do
    collection do
      post :squash_many_duplicates
      get :map
      get :duplicates
    end
  end

  resources :versions, :only => [:edit]
  resources :changes, :controller => 'paper_trail_manager/changes'
  match 'recent_changes' => redirect("/changes")
  match 'recent_changes.:format' => redirect("/changes.%{format}")

  match 'css/:name' => 'site#style'
  match 'css/:name.:format' => 'site#style'

  match '/' => 'site#index', :as => :root
  match '/index' => 'site#index'
  match '/index.:format' => 'site#index'

end

app/models/venue.rb
# == Schema Information
# Schema version: 20110604174521
#
# Table name: venues
#
#  id              :integer         not null, primary key
#  title           :string(255)
#  description     :text
#  address         :string(255)
#  url             :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  street_address  :string(255)
#  locality        :string(255)
#  region          :string(255)
#  postal_code     :string(255)
#  country         :string(255)
#  latitude        :decimal(, )
#  longitude       :decimal(, )
#  email           :string(255)
#  telephone       :string(255)
#  source_id       :integer
#  duplicate_of_id :integer
#  version         :integer
#  closed          :boolean
#  wifi            :boolean
#  access_notes    :text
#  events_count    :integer
#

class Venue < ActiveRecord::Base
  include SearchEngine
  include StripWhitespace

  has_paper_trail
  acts_as_taggable

  include VersionDiff

  xss_foliate :sanitize => [:description, :access_notes]
  include DecodeHtmlEntitiesHack

  # Associations
  has_many :events, :dependent => :nullify
  belongs_to :source

  # Triggers
  strip_whitespace! :title, :description, :address, :url, :street_address, :locality, :region, :postal_code, :country, :email, :telephone
  before_validation :normalize_url!
  before_save :geocode

  # Validations
  validates_presence_of :title
  validates_format_of :url,
    :with => /(http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/,
    :allow_blank => true,
    :allow_nil => true
  validates_inclusion_of :latitude, :longitude,
    :in => -180..180,
    :allow_nil => true,
    :message => "must be between -180 and 180"

  include ValidatesBlacklistOnMixin
  validates_blacklist_on :title, :description, :address, :url, :street_address, :locality, :region, :postal_code, :country, :email, :telephone

  include UpdateUpdatedAtMixin

  # Duplicates
  include DuplicateChecking
  duplicate_checking_ignores_attributes    :source_id, :version, :closed, :wifi, :access_notes
  duplicate_squashing_ignores_associations :tags, :base_tags, :taggings

  # Named scopes
  scope :masters,
    :conditions => ['duplicate_of_id IS NULL'],
    :include => [:source, :events, :tags, :taggings]
  scope :with_public_wifi, :conditions => { :wifi   => true }
  scope :in_business, :conditions      => { :closed => false }
  scope :out_of_business, :conditions  => { :closed  => true }

  #===[ Instantiators ]===================================================

  # Returns a new Venue for the +abstract_location+ retrieved from +source+.
  def self.from_abstract_location(abstract_location, source=nil)
    venue = Venue.new

    # TODO Figure out if +abstract_location+ can ever be blank. If it can be blank, rework the later code in this method so that #geocode and duplicate finders aren't called on an effectively blank record. If it can't be blank, remove this unnecessary "unless" conditional.
    unless abstract_location.blank?
      venue.source = source if source
      abstract_location.each_pair do |key, value|
        next if key == :tags
        venue[key] = value unless value.blank?
      end
      venue.tag_list = abstract_location.tags.join(',')
    end

    # We must add geocoding information so this venue can be compared to existing ones.
    venue.geocode

    # if the new venue has no exact duplicate, use the new venue
    # otherwise, find the ultimate master and return it
    duplicates = venue.find_exact_duplicates

    if duplicates.present?
      venue = duplicates.first.progenitor
    else
      venue_machine_tag_name = abstract_location.tags.find { |t|
        # Match 2 in the MACHINE_TAG_PATTERN is the predicate
        ActsAsTaggableOn::Tag::VENUE_PREDICATES.include? t.match(ActsAsTaggableOn::Tag::MACHINE_TAG_PATTERN)[2]
      }
      matched_venue = Venue.tagged_with(venue_machine_tag_name).first

      venue = matched_venue.progenitor if matched_venue.present?
    end

    return venue
  end

  #===[ Finders ]=========================================================

  # Return Hash of Venues grouped by the +type+, e.g., a 'title'. Each Venue
  # record will include an <tt>events_count</tt> field containing the number of
  # events at the venue, which improves performance for displaying these.
  def self.find_duplicates_by_type(type='na')
    case type
    when 'na', nil, ''
      # The LEFT OUTER JOIN makes sure that venues without any events are also returned.
      return { [] => \
        self.where('venues.duplicate_of_id IS NULL').order('LOWER(venues.title)')
      }
    else
      kind = %w[all any].include?(type) ? type.to_sym : type.split(',')

      return self.find_duplicates_by(kind, 
        :grouped  => true, 
        :where    => 'a.duplicate_of_id IS NULL AND b.duplicate_of_id IS NULL'
      )
    end
  end

  #===[ Address helpers ]=================================================

  # Does this venue have any address information?
  def has_full_address?
    return [street_address, locality, region, postal_code, country].any?(&:present?)
  end

  # Display a single line address.
  def full_address
    if has_full_address?
      "#{street_address}, #{locality} #{region} #{postal_code} #{country}"
    else
      nil
    end
  end

  #===[ Geocoding helpers ]===============================================

  @@_is_geocoding = true

  # Should geocoding be performed?
  def self.perform_geocoding?
    return @@_is_geocoding
  end

  # Set whether to perform geocoding to the boolean +value+.
  def self.perform_geocoding=(value)
    return @@_is_geocoding = value
  end

  # Run the block with geocoding enabled, then reset the geocoding back to the
  # previous state. This is typically used in tests.
  def self.with_geocoding(&block)
    original = self.perform_geocoding?
    begin
      self.perform_geocoding = true
      block.call
    ensure
      self.perform_geocoding = original
    end
  end

  # Get an address we can use for geocoding
  def geocode_address
    full_address or address
  end

  # Return this venue's latitude/longitude location,
  # or nil if it doesn't have one.
  def location
    [latitude, longitude] unless latitude.blank? or longitude.blank?
  end

  # Should we default to forcing geocoding when the user edits this venue?
  def force_geocoding
    location.nil? # Yes, if it has no location.
  end

  # Maybe trigger geocoding when we save
  def force_geocoding=(force_it)
    self.latitude = self.longitude = nil if force_it
  end

  # Try to geocode, but don't complain if we can't.
  # TODO Consider renaming this to #add_geocoding! to imply that this method makes destructive changes the object, rather than just returning values. Compare its name to the method called #geocode_address, which just returns values.
  def geocode
    if self.class.perform_geocoding? && location.blank? && geocode_address.present? && duplicate_of.blank?
      geo = GeoKit::Geocoders::MultiGeocoder.geocode(geocode_address)
      if geo.success
        self.latitude       = geo.lat
        self.longitude      = geo.lng
        self.street_address = geo.street_address if self.street_address.blank?
        self.locality       = geo.city           if self.locality.blank?
        self.region         = geo.state          if self.region.blank?
        self.postal_code    = geo.zip            if self.postal_code.blank?
        self.country        = geo.country_code   if self.country.blank?
      end

      msg = 'Venue#add_geocoding for ' + (self.new_record? ? 'new record' : "record #{self.id}") + ' ' + (geo.success ? 'was successful' : 'failed') + ', response was: ' + geo.inspect
      Rails.logger.info(msg)
    end

    return true
  end

  #===[ Triggers ]========================================================

  def normalize_url!
    unless self.url.blank? || self.url.match(/^[\d\D]+:\/\//)
      self.url = 'http://' + self.url
    end
  end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  include SquashManyDuplicatesMixin # Provides squash_many_duplicates

  # GET /venues
  # GET /venues.xml
  def index
    scoped_venues = Venue.non_duplicates

    # Pick a subset of venues (we want in_business by default)
    if params[:include_closed]
      scoped_venues = scoped_venues
    elsif params[:closed]
      scoped_venues = scoped_venues.out_of_business
    else
      scoped_venues = scoped_venues.in_business
    end

    # Support old ajax autocomplete parameter name
    params[:term] = params[:val] if params[:val]

    @tag = nil
    if params[:tag].present? # searching by tag
      @tag = params[:tag]
      @venues = scoped_venues.tagged_with(@tag)
    elsif params.has_key?(:query) || params.has_key?(:term) || params[:all] == '1' # searching by query
      scoped_venues = scoped_venues.with_public_wifi if params[:wifi]

      if params[:term].present? # for the ajax autocomplete widget
        conditions = ["title LIKE :query", {:query => "%#{params[:term]}%"}]
        @venues = scoped_venues.find(:all, :order => 'lower(title)', :conditions => conditions)
      elsif params[:query].present?
        @venues = Venue.search(params[:query], :include_closed => params[:include_closed], :wifi => params[:wifi])
      else
        @venues = scoped_venues.all
      end
    else # default view
      @most_active_venues = scoped_venues.limit(10).order('events_count DESC')
      @newest_venues = scoped_venues.limit(10).order('created_at DESC')
    end

    @page_title = "Venues"

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml  => @venues || scoped_venues }
      format.json { render :json => @venues || scoped_venues, :callback => params[:callback] }
      format.js   { render :json => @venues || scoped_venues, :callback => params[:callback] }
      format.kml  { @venues ||= scoped_venues; render } # index.kml.erb
    end
  end

  # GET /venues/map
  def map
    @venues = Venue.non_duplicates.in_business
  end

  # GET /venues/1
  # GET /venues/1.xml
  def show
    begin
      @venue = Venue.find(params[:id], :include => :source)
    rescue ActiveRecord::RecordNotFound => e
      flash[:failure] = e.to_s
      return redirect_to(venues_path)
    end

    return redirect_to(venue_url(@venue.duplicate_of)) if @venue.duplicate?

    @page_title = @venue.title

    respond_to do |format|
      format.html {
        @future_events = @venue.events.order("start_time ASC").future.non_duplicates.includes(:venue)
        @past_events = @venue.events.order("start_time DESC").past.non_duplicates.includes(:venue)
      }
      format.xml  { render :xml => @venue }
      format.json  { render :json => @venue, :callback => params[:callback] }
      format.ics  { ical_export(@venue) }
    end
  end

  # GET /venues/new
  # GET /venues/new.xml
  def new
    @venue = Venue.new
    @page_title = "Add a Venue"

    respond_to do |format|
      format.html { render :layout => !(params[:layout]=="false") }
      format.xml  { render :xml => @venue }
    end
  end

  # GET /venues/1/edit
  def edit
    @venue = Venue.find(params[:id])
    @page_title = "Editing '#{@venue.title}'"
  end

  # POST /venues
  # POST /venues.xml
  def create
    @venue = Venue.new(params[:venue])

    if evil_robot = !params[:trap_field].blank?
      flash[:failure] = "<h3>Evil Robot</h3> We didn't create this venue because we think you're an evil robot. If you're really not an evil robot, look at the form instructions more carefully. If this doesn't work please file a bug report and let us know."
    end

    respond_to do |format|
      if !evil_robot && @venue.save
        flash[:success] = 'Venue was successfully created.'
        format.html { redirect_to( venue_path(@venue) ) }
        format.xml  { render :xml => @venue, :status => :created, :location => @venue }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @venue.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /venues/1
  # PUT /venues/1.xml
  def update
    params[:venue][:latitude] = params[:venue][:longitude] = nil if params[:venue][:force_geocoding]=="1" unless params[:venue].blank?
    @venue = Venue.find(params[:id])
    
    if evil_robot = !params[:trap_field].blank?
      flash[:failure] = "<h3>Evil Robot</h3> We didn't update this venue because we think you're an evil robot. If you're really not an evil robot, look at the form instructions more carefully. If this doesn't work please file a bug report and let us know."
    end

    respond_to do |format|
      if !evil_robot && @venue.update_attributes(params[:venue])
        flash[:success] = 'Venue was successfully updated.'
        format.html { 
          if(!params[:from_event].blank?)
            redirect_to(event_url(params[:from_event]))
          else
            redirect_to( venue_path(@venue) )
          end
          }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @venue.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.xml
  def destroy
    @venue = Venue.find(params[:id])

    if @venue.events.count > 0
      message = "Cannot destroy venue that has associated events, you must reassociate all its events first."
      respond_to do |format|
        format.html {
          flash[:failure] = message
          redirect_to( venue_path(@venue) )
        }
        format.xml {
          render :xml => message, :status => :unprocessable_entity
        }
      end
    else
      @venue.destroy
      respond_to do |format|
        format.html { redirect_to(venues_path, :flash => {:success => "\"#{@venue.title}\" has been deleted"}) }
        format.xml { head :ok }
      end
    end
  end

  # GET /venues/duplicates
  def duplicates
    @type = params[:type]
    begin
      @grouped_venues = Venue.find_duplicates_by_type(@type)
    rescue ArgumentError => e
      @grouped_venues = {}
      flash[:failure] = "#{e}"
    end

    @page_title = "Duplicate Venue Squasher"

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @grouped_venues }
    end
  end

protected

  def ical_export(venue)
    events = venue.events.order("start_time ASC").non_duplicates
    render(:text => Event.to_ical(events, :url_helper => lambda{|event| event_url(event)}), :mime_type => 'text/calendar')
  end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= semantic_form_for(venue, :html => {:id => 'venue_form', :class => 'standard_form', :novalidate => 'novalidate'}) do |f| %>
  <%= f.inputs :name => "#{'Editing: ' unless venue.new_record?} <em>#{venue.title}</em>".html_safe do %>
    <li class='input'>
      <p class='inline-hints'>You can <%= venue.new_record? ? "enter" : "edit" %> the details of your venue below.  The more information we have about your venue, the easier it will be for people to find it.</p>
    </li>
    <%= f.input :title, :label => "Venue Name" %>
    <% focus_on '#venue_title' %>
    <%= f.input :address, :label => "Full Address", :hint => "(one-line version of full address)" %>

    <% unless venue.new_record? %>
      <%= f.input :street_address %>
      <%= f.input :locality, :label => "City" %>
      <%= f.input :region, :label => "State" %>
      <%= f.input :postal_code, :label => "Zip Code" %>
      <%= f.input :latitude,  :input_html => { :maxlength => 20 } %>
      <%= f.input :longitude, :input_html => { :maxlength => 20 } %>
    <% end %>

    <%= f.input :url, :label => "Web Link" %>
    <%= f.input :email %>
    <%= f.input :telephone %>
    <%= f.input :wifi, :label => "This venue has public wireless internet access" %>
    <%= f.input :description,
                :input_html => {:rows => 12},
                :hint => "(Format text using #{link_to("Markdown", "http://www.simpleeditions.com/59001/markdown-an-introduction", :target => "_blank")} and HTML)".html_safe %>
    <%= f.input :access_notes,
                :input_html => {:rows => 4},
                :hint => "(Details about how to access the space, and any accessibility restrictions that visitors may want to know about.)" %>

    <%= f.input(:closed, :label => "This venue is no longer open for business") unless venue.new_record? %>

    <%= f.input :tag_list, :required => false,
                :label => 'Tags',
                :hint => "(Tags are comma-separated keywords that make it easier to find your event and boost its position in searches. You can also use a tag like <code>plancast:plan=ABCD</code> to associate this with a particular <a href='http://plancast.com/'>Plancast</a> event, or a tag like <code>epdx:group=1234</code> to associate the event with a particular <a href='http://epdx.org/'>ePDX</a> group)".html_safe %>

    <% unless venue.new_record? %>
      <%= f.input :force_geocoding,
                  :label => venue.location ? "Re-geocode?" : "Geocode?",
                  :as => :boolean,
                  :hint => venue.location \
                            ? "([#{venue.latitude}, #{venue.longitude}] currently; if checked, we'll try again.)" \
                            : "(if checked, we'll try to determine a map position for this venue.)" %>
    <% end %>

    <li class='trap'>
      <%= label 'trap', 'field', "Leave this field blank or we'll think you're a robot." %>
      <%= text_field_tag 'trap_field', params[:trap_field] %>
    </li>

    <% if !params[:from_event].blank? %>
      <%= hidden_field_tag(:from_event, params[:from_event]) %>
    <% end %>
  <% end %>

  <%= f.actions :submit %>
<% end %>

app/views/venues/_subnav.html.erb
<div id="venues_subnav" class="subnav">
    <ul class="clearfix">
      <li><%= link_to 'Browse venues', venues_url, 
              :class => subnav_class_for("venues", "index") %>
      </li>
      <li><%= link_to 'Add a venue', new_venue_url,
              :class => subnav_class_for("venues", "new") %>
      </li>
    </ul>
</div>

app/views/venues/duplicates.html.erb
<div id="venues_duplicates">
  <h1>Duplicate Venues</h1>

  <div id='list_filters' class='sidebar'>
    <h3>Show venues with a duplicate</h3>
    <ul>
      <li><%= link_to_unless_current "Title", url_for(:action => 'duplicates', :type => 'title') %></li>
      <li><%= link_to_unless_current "Address", url_for(:action => 'duplicates', :type => 'address') %></li>
      <li><%= link_to_unless_current "Street Address", url_for(:action => 'duplicates', :type => 'street_address') %></li>
      <li><%= link_to_unless_current "Postal Code", url_for(:action => 'duplicates', :type => 'postal_code') %></li>
      <li><%= link_to_unless_current "URL", url_for(:action => 'duplicates', :type => 'url') %></li>
      <li><%= link_to_unless_current "Description", url_for(:action => 'duplicates', :type => 'description') %></li>
      <li><%= link_to_unless_current "Geo. Coords", url_for(:action => 'duplicates', :type => 'latitude,longitude') %></li>
      <li><%= link_to_unless_current "Email", url_for(:action => 'duplicates', :type => 'email') %></li>
      <li><%= link_to_unless_current "Telephone", url_for(:action => 'duplicates', :type => 'telephone') %></li>
      <li>-----</li>
      <li><%= link_to_unless_current "Any Field", url_for(:action => 'duplicates', :type => 'any') %></li>
      <li><%= link_to_unless_current "All Fields", url_for(:action => 'duplicates', :type => 'all') %></li>
    </ul>
    <h3>List venues</h3>
    <ul>
      <li><%= link_to_unless_current "All Venues", url_for(:action => 'duplicates', :type => 'na') %></li>
    </ul>
  </div>

  <% unless @grouped_venues.empty? %>
    <%= form_tag :action => "squash_many_duplicates", :method => :post %>
      <div class="flash notice">
        Select only one set of master and duplicate venues. If you select an unrelated venue, it will be merged into the same single master record.
      </div>
      <div id='list_items'>
        <%= hidden_field_tag(:type, @type) %>
        <table>
          <% for value, group in @grouped_venues %>
            <tr>
              <th>Master?</th><th>Duplicate?</th><th># of Events</th><th>Venue<%= " (#{value})" unless value.blank? %></th>
            </tr>
            <% for venue in group %>
              <tr class="<%= cycle('odd', 'even') %>">
                <td><%= radio_button_tag("master_id", venue.id) %></td>
                <td><%= check_box_tag("duplicate_id_#{venue.id}", venue.id) %></td>
                <td><%= venue.events_count %></td>
                <td>
                  <%= link_to(venue.title, venue_url(venue)) %>
                  <% if venue.has_full_address? %>
                    at <%= venue.full_address %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </table>
        <ul>
          <li>Checked items will be deleted.</li>
          <li>Events associated with deleted venues will be replaced with the venues selected using radio buttons.</li>
        </ul>
        <%= submit_tag "Squash Duplicates" %>
      </div>
    </form>
  <% else %>
    No duplicates found
  <% end %>
</div>

app/views/venues/edit.html.erb
<%= render '/versions/edit_with_chooser', :record => @venue %>

app/views/venues/index.html.erb
<% tabindex_on '#search_field' %>
<div id="venues_index">
<h1>Venues</h1>
<div id='venues_search'>
  <h2>Find a venue:</h2>
  <%= form_tag venues_path, :method => 'get' do %>
    <div class='keywords'>
      <%= label_tag :query, "Keywords" %>
      <%= text_field_tag :query, params[:query] %>
    </div>
    <div class='wifi'>
      <%= check_box_tag :wifi, '1', params[:wifi] %>
      <%= label_tag :wifi, "Public WiFi" %>
    </div>

    <div class='submit'>
      <%= submit_tag "Search" %>
    </div>
  <% end %>
</div>

<% if @venues %>
  <div id='venues_search_results'>
    <div id='list_description'>
      <% if @tag %>
        <h2>Showing <strong><%= @venues.size %></strong> venues tagged with <strong><%= @tag %></strong></h2>
      <% else -%>
        <h2>
          <% if @venues.size == 0 -%>
            Sorry, there are no venues
          <% else -%>
            Showing <%= "all " if params[:all] %><strong><%= @venues.size %></strong> <%= 'venue'.pluralize(@venues.size) %>
          <% end %>
          <% if params[:query].present? %>
            matching &#8220;<%= params[:query] %>&#8221;
          <% end %>
          <%= "with public WiFi" if params[:wifi] %>
        </h2>
      <% end -%>
    </div>

    <ul>
      <% for venue in @venues %>
        <li>
          <%= link_to(venue.title, venue_url(venue)) %>
          <% if venue.has_full_address? %>
            <p class='detail'><%= venue.full_address %></p>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
<% else %>
  <div id='venue_portal'>
    <div id='most_active'>
      <h3>Most Active</h3>
      <ul>
        <% for venue in @most_active_venues %>
          <li>
            <%= link_to(venue.title, venue_url(venue)) %>
            <p class='detail'><%= venue.events_count %> events</p>
          </li>
        <% end %>
      </ul>
    </div>
    <div id='newest'>
      <h3>Newest</h3>
      <ul>
        <% for venue in @newest_venues %>
          <li>
            <%= link_to(venue.title, venue_url(venue)) %>
            <p class='detail'>Added <%= time_ago_in_words(venue.created_at) %> ago</p>
          </li>
        <% end %>
      </ul>
    </div>
    <div id="exports">
      <ul>
        <li><%= link_to 'List all venues', venues_path(:all => 1) %></li>
        <li><%= link_to 'View a big map', map_venues_path %></li>
      </ul>
      <h3>Export venues</h3>
      <ul>
        <li><%= link_to 'KML', '/venues.kml' %></li>
        <li><%= link_to 'JSON', '/venues.json' %></li>
      </ul>
    </div>
  </div>
  <% end %>
</div>

app/views/venues/index.kml.erb
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.2">
  <Document>
  <% for venue in @venues -%>
  <% next if venue.latitude.nil? -%>
  <Placemark>
    <name><%= escape_once(venue.title) %></name>
    <description><%= cdata_section(venue.description) %></description>
    <Point>
      <coordinates><%= venue.longitude %>,<%= venue.latitude %></coordinates>
    </Point>
  </Placemark>
  <% end -%>
  </Document>
</kml>

app/views/venues/map.html.erb
<h1>Big Map of Venues</h1>
<div id='venues_map'>
  <%= google_map @venues, SETTINGS.venues_google_map_options %>
</div>

app/views/venues/new.html.erb
<div id="new_venue_form">
  <%= render :partial => 'form', :locals => {:venue => @venue} %>
</div>

app/views/venues/show.html.erb
<% tabindex_on '#search_field' %>

<% content_for :discovery_insert do %>
  <link rel="alternate" type="application/x-wiki" title="Edit this page" href="<%= edit_venue_url(@venue) %>" />
<% end %>

<div class="single_venue contentbar">
  <a href="#" id="venue_sidebar_toggle" class="expander_toggle">Export or edit this venue...</a>
  <div id="venue_sidebar" class='single_view_right sidebar'>
    <div id='edit_link'>
      <p>
        You can <%= link_to "edit", edit_venue_url(@venue) %>
        or <%= link_to "delete", venue_url(@venue), :method => :delete, :confirm => "Are you sure?" %>
        this venue.
      </p>
    </div>
    <hr />
    <p>Download an <%= link_to "iCalendar file", venue_url(@venue, :format => :ics) %> or
    <%= link_to "subscribe to a feed", venue_url(@venue, :format => :ics, :protocol => "webcal") %> of events at this venue.</p>
    <hr />
    <div class="metadata">
      <%= datestamp(@venue) %>
    </div>
  </div>

  <div class="location vcard<%= " closed" if @venue.closed? %>">
    <h1 class="fn org"><%= @venue.title %></h1>
    <% if @venue.closed? %><p class='closed_callout'>This venue is no longer open for business.</p><% end %>

    <% if @venue.has_full_address? %>
      <div class="adr">
        <% if @venue.street_address.present? %>
          <div class="street-address"><%= @venue.street_address %></div>
        <% end %>
        <% if @venue.locality.present? %>
          <span class="locality"><%= @venue.locality %></span><%= "," if @venue.region.present? or @venue.postal_code.present? or @venue.country.present? %>
        <% end %>
        <% if @venue.region.present? %>
          <span class="region"><%= @venue.region %></span><%= "," if @venue.country.present? and not @venue.postal_code.present? %>
        <% end %>
        <% if @venue.postal_code.present? %>
          <span class="postal-code"><%= @venue.postal_code %></span><%= "," if  @venue.country.present? %>
        <% end %>
        <% if @venue.country.present? %>
          <span class='country-name'><%= @venue.country %></span>
        <% end %>
        (<a href='<%=google_maps_url(@venue.full_address) -%>'>map</a>)
      </div>
    <% else %>
      <% if @venue.address.present? %>
        <div class='address'>
          <%= @venue.address %>
          (<a href='<%=google_maps_url(@venue.address) -%>'>map</a>)
        </div>
      <% end %>
    <% end %>

    <div class='info'>
      <% if @venue.url.present? %>
        <div class='url'><%= link_to(truncate(url_for(@venue.url), :length => 60), url_for(@venue.url), :rel => "nofollow") %></div>
      <% end %>

      <% if @venue.email.present? %>
        <div class='email'><%= mail_to @venue.email %></div>
      <% end %>

      <% if @venue.telephone.present? %>
        <div class='tel'><%= @venue.telephone %></div>
      <% end %>

      <% if @venue.wifi? %>
        <div class='wifi_callout'>Public WiFi</div>
      <% end %>
    </div>
  </div>

  <% if @venue.description.present? || @venue.access_notes.present? %>
    <div class="description">
      <%= format_description(@venue.description) %>
      <% if @venue.access_notes.present? %>
        <div class="access_notes">
          <h3>Access Notes</h3>
          <%= format_description @venue.access_notes %>
        </div>
      <% end %>
    </div>
  <% end %>

  <% if @venue.tags.present? -%>
    <div class="tags">
      <h2>Tags</h2>
      <%= tag_links_for @venue %>
    </div>
  <% end %>

  <div id="google_map">
    <%= google_map @venue %>
  </div>

  <div id='events'>
    <div id='future_events'>
      <h2>Future events happening here</h2>
      <%= render :partial => 'events/list', :locals => { :events => @future_events } %>
    </div>

    <div id='past_events'>
      <h2>Past events that happened here</h2>
      <%= render :partial => 'events/list', :locals => { :events => @past_events } %>
    </div>
  </div>
</div>